### ISSUE TITLE
Como administrador quiero poder dar de baja al dueño de un negocio (Grupo 2)

### ISSUE THREAD

**Issue by TeddyAP98** [sis313/sistemaII2022#3]

**Comment by JuancaJcA** [comment]
- [x]  Base de datos (2 hrs)
- [x] Crear listado (3 hrs)
- [x] Hacer prueba del listado (3 hrs)
- [x] Crear botones (3 hrs)
- [x] Crear alerta de confirmación (3hrs)

**Comment by TeddyAP98** [comment]
- [x] Crear conexion con la base de datos (4 hrs)
- [x] Crear metodo para el borrado del dueño del negocio (4 hrs)
- [x] Crear metodos para la validacion (4 hrs)
- [x] Listar los dueños existentes(4 hrs)
- [x] Probar el borrado (4 hrs)
