### ISSUE TITLE
Como administrador quiero habilitar un dueño de negocio previamente deshabilitado (Grupo 2)

### ISSUE THREAD

**Issue by NoeliaVasquezCrespo** [sis313/sistemaII2022#35]

**Comment by JuancaJcA** [comment]
- [x] Crear funciones en la base de datos para mostrar negocios deshabilitados (2hrs.)
- [x] Verificar salida adecuada de los datos (4 hrs.)
- [x] Modificar el frontend para un apartado personalizado que indique estos negocios deshabilitados (5 hrs.)
- [x] Crear el botón para habilitar estos negocios (2 hrs).
- [x] Verificar el funcionamiento de manera general (4 hrs).
