### ISSUE TITLE
Integrar frontend con el servidor donde se almacena el backend (Grupo 2)

### ISSUE THREAD

**Issue by NoeliaVasquezCrespo** [sis313/sistemaII2022#37]

**Comment by JosephColbertM** [comment]
- [x]  Modificar la ruta a la del servidor [2Hrs]
- [x] Comprobar el funcionamiento del servidor segun las rutas [4Hrs]
- [x] Cambiar cada ruta que corresponde en los servicios del frontend [7Hrs]
- [x] Verificar que la integracion con el servidor sea la correcta [1Hrs]
- [x] Comprobar el funcionamiento del frontend con el backend [2Hrs]
