### ISSUE TITLE
Como administrador quiero habilitar un negocio previamente deshabilitado (Grupo 2)

### ISSUE THREAD

**Issue by TeddyAP98** [sis313/sistemaII2022#4]

**Comment by Mauro8500** [comment]
- [x] Validar campos del negocio[3Hrs]
- [x] Generar una conexion para el cambio de estados en BDD [5Hrs]
- [x] Cambiar la interfaz de administrador [5hrs]
- [x] Creacion y validacion de listas en el backend [5Hrs]
- [x] Mejora en el diseño y la interfaz [2Hrs]

**Comment by NoeliaVasquezCrespo** [comment]
- [x] Generación de nuevo métodos para la recuperación de negocio [2Hrs]
- [x] Crear una interfaz con la lista de negocios inhabilitados[2Hrs]
- [x] Cargar las nuevas listas de negocios[3Hrs]
- [x] Validar campos en la nueva interfaz con un botón [5Hrs]
- [x] Crear métodos que permitan la validación de cambio de estado de los negocios [10Hrs]
